# Generated by Django 3.2.5 on 2021-11-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0003_auto_20211110_0659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='a_name',
            new_name='album_name',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='a_name',
            new_name='album_name',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
