# Generated by Django 3.2.5 on 2021-11-10 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0004_auto_20211110_0707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='geo_comment',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='image',
            name='date_uploaded',
        ),
    ]
