# Generated by Django 3.2.5 on 2021-11-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0005_auto_20211110_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='date_uploaded',
            field=models.DateField(blank=True, null=True),
        ),
    ]
