# Generated by Django 3.2.5 on 2021-11-21 10:15

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import image_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0007_goods'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/my_sell/', location='/Users/chrisjanrebel/Documents/GitHub/CMPG323_Pro2/CMPG_Proj2/media/my_sell/'), upload_to=image_app.models.image_directory_path)),
                ('title', models.CharField(max_length=15, unique=True)),
                ('desc', models.CharField(max_length=300, unique=True)),
                ('location', models.CharField(max_length=30, unique=True)),
                ('date_uploaded', models.DateField(blank=True, null=True)),
                ('album_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_in_album', to='image_app.album')),
            ],
        ),
        migrations.DeleteModel(
            name='Goods',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
