# Generated by Django 3.2.5 on 2021-11-21 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0008_auto_20211121_1015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userimage',
            options={'ordering': ('-date_uploaded',)},
        ),
    ]
