# Generated by Django 3.2.5 on 2021-11-21 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0009_alter_userimage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userimage',
            options={'ordering': ('date_uploaded',)},
        ),
    ]
