# Generated by Django 3.2.5 on 2021-11-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0010_alter_userimage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='location',
            field=models.CharField(max_length=30),
        ),
    ]
